spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.media-biz.host:3306/kk_point_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: adiscope
    password: doeltmzhq12#
    hikari:
      poolName: Hikari
      maximum-pool-size: 30
      max-lifetime: 1800000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: cache.media-biz.host
  jpa:
    properties:
      hibernate:
        format_sql: false

cloud:
  aws:
    s3:
      bucket: trot-static

static.domain: https://trot-static.idol-master.kr

trot.sns.ios.env: production

logging:
  config: classpath:logback-json.xml
  level:
    root: ERROR
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
